### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by AykutCevik** [esendex/esendex-php-sdk#5]
Hi guys,
first, your service is awesome!
But I have a question according to this sdk, especially the HttpClient-class.

Why do you need to send so much information in the user agent section like the **running OS, UTC time, bit-computing architecture and software running on the server**?
Sadly, I'm not able to use this library in this state and will implement it on the given REST architecture on my own.

Regards,

**Comment by Codesleuth** [comment]
Hello @AykutCevik!

The user agent properties are there simply for analytics - the SDK can operate perfectly fine without them. Although we wouldn't like to remove them ourselves, I would suggest that you fork the repository and remove those elements from the HttpClient, then use your fork instead of the official client.

We would welcome a pull request if you can alter the SDK to gracefully disable these UA properties, without breaking existing integrations.

Cheers!

**Comment by AykutCevik** [comment]
Hi @Codesleuth,

thank you for your reply and suggestion. 

Cheers.
